"""update full

Revision ID: 015c8dcf4f90
Revises: 0fec19c24cab
Create Date: 2025-07-15 16:09:07.860075

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "015c8dcf4f90"
down_revision: Union[str, Sequence[str], None] = "0fec19c24cab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "login_sessions", sa.Column("finger_print", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_login_sessions_finger_print"),
        "login_sessions",
        ["finger_print"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_sessions_finger_print"), table_name="login_sessions")
    op.drop_column("login_sessions", "finger_print")
    # ### end Alembic commands ###
