"""fix string id

Revision ID: 1ba7cfad0750
Revises: 86fa8bf846e4
Create Date: 2025-07-05 15:05:47.491731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba7cfad0750'
down_revision: Union[str, Sequence[str], None] = '86fa8bf846e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_predictions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_asset_predictions_id'), table_name='asset_predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_asset_predictions_id'), 'asset_predictions', ['id'], unique=False)
    op.alter_column('asset_predictions', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
