"""Add created_at to pipelines

Revision ID: 257fadda6f17
Revises: 7530492cca93
Create Date: 2025-06-26 23:42:57.100187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '257fadda6f17'
down_revision: Union[str, Sequence[str], None] = '7530492cca93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('pipelines', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pipelines', 'created_at')
    # ### end Alembic commands ###
