"""update fix column add end time

Revision ID: 6360653d4712
Revises: 1d7449fb37cb
Create Date: 2025-07-01 20:18:59.408200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6360653d4712'
down_revision: Union[str, Sequence[str], None] = '1d7449fb37cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_predictions', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_predictions', 'end_time')
    # ### end Alembic commands ###
