"""add column provider account id

Revision ID: d7582b0a0eef
Revises: bf2822dd953d
Create Date: 2025-07-03 16:14:06.335836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7582b0a0eef'
down_revision: Union[str, Sequence[str], None] = 'bf2822dd953d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('provider_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'provider_account_id')
    # ### end Alembic commands ###
