"""Add BitcoinPrice table

Revision ID: e46c90ef1321
Revises: cc74e353a17d
Create Date: 2025-06-27 14:20:38.064771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46c90ef1321'
down_revision: Union[str, Sequence[str], None] = 'cc74e353a17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitcoin_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitcoin_price_id'), 'bitcoin_price', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitcoin_price_id'), table_name='bitcoin_price')
    op.drop_table('bitcoin_price')
    # ### end Alembic commands ###
