"""fixed update message add index account_id and timestamp

Revision ID: e975dd406ee1
Revises: 6200f54d0822
Create Date: 2025-07-26 10:27:34.935440

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e975dd406ee1"
down_revision: Union[str, Sequence[str], None] = "6200f54d0822"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_account_time", "messages", ["account_id", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_messages_account_id"), "messages", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_timestamp"), "messages", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_timestamp"), table_name="messages")
    op.drop_index(op.f("ix_messages_account_id"), table_name="messages")
    op.drop_index("idx_account_time", table_name="messages")
    # ### end Alembic commands ###
