"""add column provider account id

Revision ID: f43d2a6e2690
Revises: d7582b0a0eef
Create Date: 2025-07-03 17:28:55.429934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43d2a6e2690'
down_revision: Union[str, Sequence[str], None] = 'd7582b0a0eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'provider_account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'provider_account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
